### ISSUE TITLE
Jar with Dependencies - Does this library need all those "dependencies" ?

### ISSUE THREAD

**Issue by homerlex** [MarketSquare/robotframework-seleniumlibrary-java#62]
The [jar with dependencies](http://central.maven.org/maven2/com/github/hi-fi/robotframework-seleniumlibrary/3.12.0.1/robotframework-seleniumlibrary-3.12.0.1-jar-with-dependencies.jar) is pretty sizable.  Does the Selenium library actually need everything that is in there?

**Comment by Hi-Fi** [comment]
Currently that's directly from Maven.  There might be something extra, but currently at least I don't recall any removals. For the size sense Robot itself is quite big jar.

**Comment by ractoc** [comment]
it might be worth investigating of they are all really needed, and then use an <exclude> to make sure the ones that are not needed are not included

**Comment by Hi-Fi** [comment]
I'll remove those in 4.x version, and make some better approach if someone is using those (mainly Appium).

**Comment by Hi-Fi** [comment]
Current pre-releases of Selenium4 using libraries have those dependecies as "provided". so those are not in fat jar.
