### ISSUE TITLE
Request for Create Webdriver keyword in Java SeleniumLibrary RF

### ISSUE THREAD

**Issue by ishan9** [MarketSquare/robotframework-seleniumlibrary-java#65]
'Create Webdriver' keyword as part of Java SeleniumLibrary, Version 3.14.0.0 

This keyword provides more flexibility then Open Browser, in case we need to handle multiple browser, we need to have object of each webdriver, and this keyword returns the index of the browser instance.

As this keyword is part of Python RF (refer doc: http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Create%20Webdriver)
I can request if this can be included in Java SeleniumLibrary

Thanks,
Ishan

**Comment by Hi-Fi** [comment]
Can you elaborate why that keyword is needed? Multiple browsers can be handled with Open browser, too (as done in https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/blob/master/src/test/robotframework/testsuites/UnitTests/AW3Schools.robot#L18). Also Open browser allows giving more variables to browser directly than Python version does.

**Comment by ractoc** [comment]
I think the main reason would be to allow for the exact same script to work both in Python and on Java. This is usefull for when you are developing the scripts in Ride or RED for example, and running them from Maven as part of a release pipeline. This is what I'm doing.

As it stands, I have to do something ugly like this:

```
Start Chrome
    [Arguments]    ${URL}
    ${status}    ${value}    Run Keyword And Ignore Error    Start Chrome For Python    ${URL}  
    Run Keyword Unless    '${status}' == 'PASS'    Start Chrome For Java    ${URL} 
```

**Comment by Hi-Fi** [comment]
@ishan9 Can you provide example how you want to use that keyword. If checking the examples from [Python version documentation](http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Create%20Webdriver), those are not working as it's not possible to evaluate Python selenium things with Java-version. So with that kind of approach there's just no possibility to make "drop in" replacement.

**Comment by Hi-Fi** [comment]
No example -> closing.
