### ISSUE TITLE
Release initial version with Selenium 4

### ISSUE THREAD

**Issue by Hi-Fi** [MarketSquare/robotframework-seleniumlibrary-java#71]

**Comment by donzellt** [comment]
Hi @ Hi-Fi,

Do you know when the release is scheduled?

Thanks this lib is really helpful for us.

**Comment by Hi-Fi** [comment]
Actually there is already versions published with Selenium 4 pre-releases. Currently Selenium 4 is at rc.

**Comment by donzellt** [comment]
Oh yes thank you but the released pre-versions do not contain the update for the bonigarcia/webdrivermanager dependency.

Perhaps it is possible to release a more up-to-date pre-release (with the webdrivermanager update)?

(Because webdrivermanager 3.4.0 doesn't seem to work with Edge anymore 😞)

**Comment by Hi-Fi** [comment]
From first Selenium 4 version I thought that final version is 'just coming', so other dependencies are old, too, like you mentioned. 

Maybe there is need to create one more pre-release and update dependencies at same time

**Comment by Hi-Fi** [comment]
Dependencies are updated now, have to check (hopefully) tomorrow couple of small things before pushing new pre-release to Maven central. SNAPSHOT version should be pushed by pipeline soon.

**Comment by Hi-Fi** [comment]
Selenium 4 version published, closing this.

https://github.com/MarketSquare/robotframework-seleniumlibrary-java/releases/tag/4.0.0.0
