### ISSUE TITLE
Implement "Element Attribute Value Should Be"

### ISSUE THREAD

**Issue by php-coder** [MarketSquare/robotframework-seleniumlibrary-java#90]
[`Element Attribute Value Should Be`](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Element%20Attribute%20Value%20Should%20Be) is implemented in Python version and it would be great to have this implemented in this library as well.

Related to #59

**Comment by YauheniPo** [comment]
I can develop this implementation or You can use getElementAttribute and validate on the test stage

**Comment by YauheniPo** [comment]
maybe this method will help you - 'waitUntilElementAttributeValueContains' from Element class

**Comment by php-coder** [comment]
> maybe this method will help you - 'waitUntilElementAttributeValueContains' from Element class

Thanks, but as far I understand, I can't use it in the tests as this isn't a keyword.

**Comment by YauheniPo** [comment]
https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/commit/9844ad4199903b6513d7878705b93bab275a1bb7#diff-915bf959e6977f82be056672ba12c8cf

This keyword was merged to develop branch, but it does not exist in the last maven dependency ((

**Comment by Hi-Fi** [comment]
That's true, latest release was made around one month before that merge. Reason why it's not at release (only SNAPSHOT) version is that there're some other fixes that I thought that could come to same release. And still do, so trying to find time to make those couple of fixes.

**Comment by Hi-Fi** [comment]
Keyword mentioned by @YauheniPo is included in 3.141.59.26535, and just also taken to Selenium 4 branch by rebasing (not released yet).
